const typeList = Object.freeze([
  {name: '工资', tagicon: 'gongzi', type: '+'},
  {name: '兼职', tagicon: 'jianzhi', type: '+'},
  {name: '转账', tagicon: 'zhuanzhang', type: '+'},
  {name: '红包', tagicon: 'hongbao', type: '+'},
  {name: '奖金', tagicon: 'jiangjin', type: '+'},
  {name: '分红', tagicon: 'fenhong', type: '+'},
  {name: '副业', tagicon: 'fuye', type: '+'},
  {name: '基金', tagicon: 'jijin', type: '+'},
  {name: '服饰', tagicon: 'fushi', type: '-'},
  {name: '购物', tagicon: 'gouwu', type: '-'},
  {name: '餐饮', tagicon: 'canyin', type: '-'},
  {name: '房租', tagicon: 'fangzu', type: '-'},
  {name: '娱乐', tagicon: 'yule', type: '-'},
  {name: '医疗', tagicon: 'yiliao', type: '-'},
  {name: '话费', tagicon: 'huafei', type: '-'},
  {name: '化妆品', tagicon: 'huazhuangpin', type: '-'},
  {name: '护肤品', tagicon: 'hufupin', type: '-'},
  {name: '家居', tagicon: 'jiaju', type: '-'},
  {name: '健身', tagicon: 'jianshen', type: '-'},
  {name: '宠物', tagicon: 'chongwu', type: '-'},
  {name: '交通', tagicon: 'jiaotong', type: '-'},
  {name: '快递', tagicon: 'kuaidi', type: '-'},
  {name: '零食', tagicon: 'lingshi', type: '-'},
  {name: '外卖', tagicon: 'waimai', type: '-'},
  {name: '学习', tagicon: 'xuexi', type: '-'},
  {name: '烟酒', tagicon: 'yanjiu', type: '-'},
  {name: '医疗', tagicon: 'yiliao', type: '-'},
  {name: '游戏', tagicon: 'youxi', type: '-'},
  {name: '约会', tagicon: 'yuehui', type: '-'},
  {name: '电子设备', tagicon: 'dianzishebei', type: '-'},
  {name: '转账', tagicon: 'zhuanzhang', type: '-'},
  {name: '基金', tagicon: 'jijin', type: '-'},
]);

export default typeList;